language: php

php:
 - 7.2
 - 7.3

before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

script:
  - vendor/bin/phpunit

# Use container-based infrastructure
sudo: false
